language: node_js
node_js:
- 0.10

env:
  global:
  - secure: pUwKMjFmjl3ebsLCAXa5mzURvGH+MGQgO4Fb7E3JpKN8OGYZQARtlAzA/eAezuViRUWeCO62Y6/oXzfpg1qmC12H6T9XwX8ine6QTBPuq12sHl8YozX2skpUucLfMWIGWs2A67ZcEZm/eCM3b0Wryc3eOYDkbAialGpP8dGuNFI=
  - secure: HOP1T0wgGVaKgmCkFXhc+kjMdeb0ExORiRf2y+XUY3GPfPuMzNKoi2S63kAvBkaSEc9qlAUpSvmfbGcBoeNzOET+WbjtG/1LWGlmXRXbg9HoqupveQYmI/8RDIT1f3Y1ZLpc+zeFnp//UQ0Fx8pY1yYA+RQjbpBJO3lhaGrqE+M=

  matrix:
    # - MODE='check'
    # - BROWSER=Android-Chrome ARGS=''
    - BROWSER=Chrome-stable
    # - BROWSER=Chrome-beta
    # - BROWSER=Chrome-unstable
    # - BROWSER=Firefox-stable ARGS='-x -b Firefox -u'
    # - BROWSER=Firefox-beta ARGS='-x -b Firefox -u'
    # - BROWSER=Firefox-aurora ARGS='-x -b Firefox -u'
    # - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=INTERNETEXPLORER --remote-caps=version=10 --remote-caps=platform="Windows 8"'
    # - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=SAFARI --remote-caps=version=6 --remote-caps=platform="OS X 10.8"'
    # - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=IPHONE --remote-caps=version=6 --remote-caps=platform="OS X 10.8"'
    # - BROWSER=Remote ARGS='--verbose -b Remote --sauce --remote-caps=ANDROID --remote-caps=version=4.0 --remote-caps=platform=Linux'

notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io

before_install:
  - ./test/scripts/.travis-setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true